name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        ghc:
          - "9.6.3"
    runs-on: buildjet-8vcpu-ubuntu-2204
    container:
      image: ghcr.io/wolverian/ghc-musl:${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: buildjet/cache@v3
        env:
          key: ${{ runner.os }}-${{ runner.arch }}-ghc-${{ matrix.ghc }}-cabal
        with:
          path: ~/.cache/cabal
          key: ${{ env.key }}-cabal-${{ hashFiles('*.cabal', 'cabal.project', 'cabal.project.freeze') }}
          restore-keys: ${{ env.key }}-
      - name: Install dependencies
        run: |
          cabal update
          cabal build all --only-dependencies
      - name: Build executable
        run: cabal build all
      - name: Check the executable runs
        run: cabal run
