name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204
    container:
      image: ghcr.io/wolverian/ghc-musl:9.6.3
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: buildjet/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cache/cabal
          key: ${{ runner.os }}-${{ runner.arch }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: Check the executable runs
        run: cabal run
